Component/checkbox
Mobile-Bootcamp-LATAM-React-Native/WhatsUp pull request #6
Opened 2022-10-11 18:41 UTC by Rodrigo-Schar

added checkbox component

2022-10-11 20:45 UTC, Rodrigo-Schar commented
![image](https://user-images.githubusercontent.com/107278558/195194781-09074216-99d4-4801-8260-622208b823ae.png)

2022-10-11 20:46 UTC, Rodrigo-Schar commented
![image](https://user-images.githubusercontent.com/107278558/195194903-9ea321b6-b45a-4c54-8f91-cc3c9202977e.png)

2022-10-11 21:51 UTC, Rodrigo-Schar commented on src/components/Checkbox.tsx
> +    <TouchableWithoutFeedback onPress={onPress}>
i think is done check it

2022-10-11 21:54 UTC, Rodrigo-Schar commented on src/components/Checkbox.tsx
> +const Checkbox = ({text, onPress}: CheckboxProps & TouchableWithoutFeedbackProps) => {
I'm not understanding can you explain it better?

2022-10-12 00:24 UTC, gaguayovelez requested changes

2022-10-12 00:24 UTC, gaguayovelez commented on src/components/Checkbox.tsx
> +  };
```ts
setChecked(!checked);
```

2022-10-12 00:24 UTC, gaguayovelez commented on src/components/Checkbox.tsx
> +    <TouchableWithoutFeedback onPress={onPress}>
@Rodrigo-Schar you need expose the following properties:

```ts

type CheckboxProps = {
  text: string;
  value: boolean,
  onChange: (value: boolean) => void
}
```

2022-10-12 21:51 UTC, merged